### ISSUE TITLE
Starting child process with 'node index.js'

### ISSUE THREAD

**Issue by raulvillora** [bq/bitbloq-backend#27]
> Bitbloq-Server@1.2.2 start /Users/raulvilloravalencia/Documents/bitbloq-backend
> supervisor index.js

Running node-supervisor with
  program 'index.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node index.js'
Watching directory '/Users/raulvilloravalencia/Documents/bitbloq-backend' for changes.
Press rs for restarting the process.
Error retrieving stats for file: /Users/raulvilloravalencia/Documents/bitbloq-backend/node_modules/.bin/pbjs
Error retrieving stats for file: /Users/raulvilloravalencia/Documents/bitbloq-backend/node_modules/.bin/window-size
^CReceived SIGINT, killing child process...
Parent process exiting, terminating child...
Rauls-MacBook-Pro:bitbloq-backend raulvilloravalencia$ hola 2
bash: hola: command not found
Rauls-MacBook-Pro:bitbloq-backend raulvilloravalencia$ npm start

> Bitbloq-Server@1.2.2 start /Users/raulvilloravalencia/Documents/bitbloq-backend
> supervisor index.js

Running node-supervisor with
  program 'index.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node index.js'
Watching directory '/Users/raulvilloravalencia/Documents/bitbloq-backend' for changes.
Press rs for restarting the process.
Error retrieving stats for file: /Users/raulvilloravalencia/Documents/bitbloq-backend/node_modules/.bin/pbjs
Error retrieving stats for file: /Users/raulvilloravalencia/Documents/bitbloq-backend/node_modules/.bin/window-size
module.js:529
    throw err;
    ^

Error: Cannot find module './config/config.json'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raulvilloravalencia/Documents/bitbloq-backend/app/res/config.js:3:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raulvilloravalencia/Documents/bitbloq-backend/app/app.js:11:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
Program node index.js exited with code 1

Starting child process with 'node index.js'
module.js:529
    throw err;
    ^

Error: Cannot find module './config/config.json'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raulvilloravalencia/Documents/bitbloq-backend/app/res/config.js:3:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raulvilloravalencia/Documents/bitbloq-backend/app/app.js:11:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
Program node index.js exited with code 1

**Comment by raulvillora** [comment]
I've fixed the error before by creating config folder and config.json with the following code:

{
    "env": "local",
    "defaultLang": "es-ES",
    "supportedLanguages": [
        "es-ES",
        "en-GB",
        "nl-NL",
        "ru-RU",
        "it-IT",
        "eu-ES",
        "ca-ES",
        "fr-FR",
        "de-DE",
        "pt-PT",
        "gl",
        "zh-CN"
    ],
    "saveTime": 2000,
    "serverUrl_": "http://localhost:8000/bitcebloq/v1/",
    "gCloudUrl": "",
    "compilerUrl": "http://localhost:3000/",
    "bucket": "",
    "chromeAppId": "nlndpbeidnfnjpfkmlcakphlbilpokho",
    "web2boardLinkWindows": "https://github.com/bq/web2board/releases/download/Latest/windows_web2board_installer.exe",
    "web2boardLinkMac": "https://github.com/bq/web2board/releases/download/Latest/mac_web2board_installer.pkg",
    "web2boardLinkLinux": "https://github.com/bq/web2board/releases/download/Latest/linux_64_web2board_installer.zip",
    "web2boardLinkLinux32": "https://github.com/bq/web2board/releases/download/Latest/linux_32_web2board_installer.zip",
    "version": "v3.3.6"
}
----------------------------- ----------------------------- ----------------------------- --------------

Now I have the following error:

> Bitbloq-Server@1.2.2 start /Users/raulvilloravalencia/Documents/bitbloq-backend
> supervisor index.js


Running node-supervisor with
  program 'index.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node index.js'
Watching directory '/Users/raulvilloravalencia/Documents/bitbloq-backend' for changes.
Press rs for restarting the process.
Error retrieving stats for file: /Users/raulvilloravalencia/Documents/bitbloq-backend/node_modules/.bin/pbjs
Error retrieving stats for file: /Users/raulvilloravalencia/Documents/bitbloq-backend/node_modules/.bin/window-size
/Users/raulvilloravalencia/Documents/bitbloq-backend/app/app.js:16
mongoose.connect(config.mongo.uri, config.mongo.options);
                             ^

TypeError: Cannot read property 'uri' of undefined
    at Object.<anonymous> (/Users/raulvilloravalencia/Documents/bitbloq-backend/app/app.js:16:30)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raulvilloravalencia/Documents/bitbloq-backend/index.js:7:28)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
Program node index.js exited with code 1

------------------------------------------------------------------------------------------------------

I will appreciate any idea about how to fix it and why it's happening.
